/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_weiquanyun_lib_AppUninstallListener */

#ifndef _Included_com_example_weiquanyun_lib_AppUninstallListener
#define _Included_com_example_weiquanyun_lib_AppUninstallListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_weiquanyun_lib_AppUninstallListener
 * Method:    uninstallListen
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_weiquanyun_lib_AppUninstallListener_uninstallListen
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
